name: LWCTrust
version: @version@
main: org.popcraft.lwctrust.LWCTrust
api-version: "1.13"
load: STARTUP
depend: [LWC]
authors: [pop4959]
description: A trust plugin module for LWC.
website: https://github.com/pop4959/LWCTrust
commands:
  trust:
    description: Manage your protection trusts.
    permission: lwctrust.trust
    usage: /trust <add/remove/list> [player]
    aliases: [ctrust]
permissions:
  lwctrust.trust:
    description: Manage your protection trusts.
    default: true
    children:
      lwctrust.trust.add: true
      lwctrust.trust.remove: true
      lwctrust.trust.list: true
